# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('roll_no', models.IntegerField(primary_key=True, serialize=False)),
                ('course', models.CharField(choices=[('IT', 'Information Technology'), ('CS', 'Computer Science'), ('EC', 'Electronics and Communication')], max_length=2)),
                ('year', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], max_length=2)),
            ],
        ),
    ]
