# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 03:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signupapplication', '0004_auto_20160326_0855'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='seenby',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='seens',
        ),
    ]
