# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 03:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signupapplication', '0005_auto_20160326_0916'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='seenby',
            field=models.ManyToManyField(blank=True, null=True, related_name='have_seen', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notification',
            name='seens',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
